artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  storage_bucket_name: mlopstes
  source_blob_name: archive.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_cleaning:
  root_dir: artifacts/data_cleaning
  unpreprocessed_data_path: artifacts/data_ingestion
  column_text: text
  column_topic: Topic
  preprocessed_data_path: artifacts/data_cleaning
